---
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.73.0/hugo_0.73.0_Linux-64bit.deb
  - sudo dpkg -i hugo_0.73.0_Linux-64bit.deb
script:
  - hugo
deploy:
  - provider: script
    script: ./scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: develop