# Site settings
title: GabLeRoux <Developer>
email: gab@gableroux.com
description: >
  Personal site about code, ideas, technologies and anything else.
  I like to write python and work on crazy projects, read my stuff!
author: Gabriel Le Breton
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gableroux.com" # the base hostname & protocol for your site

twitter_username: gableroux
google_plus_username: GabrielLeBreton
github_username: GabLeRoux
facebook_username: gableroux

comments: true
disqus_shortname: gableroux

# Build settings
markdown: kramdown

sass:
  style: compressed
  sass_dir: _sass