baseURL = "https://gableroux.com/"
languageCode = "en-ca"
title = "GabLeRoux <Developer>"
description = "  Personal site about code, ideas, technologies and everything. I like to write python and work on crazy projects, read my stuff!"

facebook_app_id = "253381494995396"
facebook_default_image = "images/layout/sharing-gableroux.jpg"

twitter_username = "gableroux"
google_plus_username = "GabrielLeBreton"
github_username = "GabLeRoux"
facebook_username = "gableroux"
