#!/usr/bin/env bash
set -e # halt script on error
set -x # makes shell script verbose

npm install -g yarn
yarn global add bower gulp
bower install
gulp build
bundle exec htmlproofer ./_site --file-ignore /bower_components/
