#!/usr/bin/env bash
set -e # halt script on error
set -x # makes shell script verbose

# requirements
npm install -g yarn@1 bower@1 gulp@3
bower install
yarn install

# expose CI versions
npm --version
bower --version
yarn --version
gulp --version

# build
gulp build

# tests
# todo: maybe move this to rakefile
# todo: Let's try to make data-proofer-ignore ignore #, allow_hash_href may be unsafe in case I forget to add a link
bundle exec htmlproofer ./_site --file-ignore /bower_components/ --allow_hash_href
