# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "GabLeRoux hugo Theme"
license = "MIT"
licenselink = "https://github.com/gableroux/gableroux.github.io/blob/master/LICENSE.md"
description = "GabLeRoux's hugo theme based on ananke theme"
homepage = "https://github.com/theNewDynamic/gohugo-theme-ananke"
tags = ["website", "starter", "responsive", "Disqus", "blog", "Tachyons", "Multilingual", "Stackbit"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = "0.64.0"

[author]
  name = "theNewDynamic"
  homepage = "https://www.thenewdynamic.com/"
